apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vdf-web.fullname" . }}-secrets
  labels:
    {{- include "vdf-web.labels" . | nindent 4 }}
type: Opaque
stringData:
  web-password: {{ .Values.secrets.webPassword | quote }}
